import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import type { Resolution, StepResolution } from './types.ts';
import { RESOLUTION_VERSION } from './types.ts';

const HEADER =
  'File generated by QAI. Do not edit by hand — it is regenerable. It is versioned so that CI replays deterministically and so that a self-repair shows up as a review diff.';

/**
 * Sérialise dans un ordre de clés fixe.
 *
 * Ce fichier vit dans git et son diff est ce qu'un développeur relit quand une
 * réparation lui est proposée. Un ordre de clés instable rendrait ce diff
 * illisible et ruinerait l'argument de confiance du produit.
 */
function orderStep(step: StepResolution): Record<string, unknown> {
  const ordered: Record<string, unknown> = { actions: step.actions };
  if (step.captures !== undefined) ordered['captures'] = step.captures;
  if (step.assertions !== undefined) ordered['assertions'] = step.assertions;
  ordered['healedAt'] = step.healedAt ?? null;
  if (step.healNote !== undefined) ordered['healNote'] = step.healNote;
  return ordered;
}

const WIDTH = 100;

/**
 * Impression JSON compacte tant qu'une valeur tient sur une ligne.
 *
 * `JSON.stringify(x, null, 2)` éclate chaque petit objet sur cinq lignes : un
 * changement d'un mot produit alors des centaines de lignes de diff, et
 * personne ne relit ça. Or la relecture du diff *est* l'argument de confiance du
 * produit — le format d'impression n'est donc pas un détail cosmétique.
 */
function inline(value: unknown): string {
  if (Array.isArray(value)) return `[${value.map(inline).join(', ')}]`;
  if (typeof value === 'object' && value !== null) {
    const entries = Object.entries(value)
      .filter(([, item]) => item !== undefined)
      .map(([key, item]) => `${JSON.stringify(key)}: ${inline(item)}`);
    return entries.length === 0 ? '{}' : `{ ${entries.join(', ')} }`;
  }
  return JSON.stringify(value) ?? 'null';
}

function print(value: unknown, depth: number): string {
  const compact = inline(value);
  if (compact.length + depth * 2 <= WIDTH) return compact;

  const pad = '  '.repeat(depth + 1);
  const close = '  '.repeat(depth);

  if (Array.isArray(value)) {
    const items = value.map((item) => `${pad}${print(item, depth + 1)}`);
    return `[\n${items.join(',\n')}\n${close}]`;
  }

  if (typeof value === 'object' && value !== null) {
    const entries = Object.entries(value)
      .filter(([, item]) => item !== undefined)
      .map(([key, item]) => `${pad}${JSON.stringify(key)}: ${print(item, depth + 1)}`);
    return `{\n${entries.join(',\n')}\n${close}}`;
  }

  return compact;
}

export function serializeResolution(resolution: Resolution): string {
  const document: Record<string, unknown> = {
    $comment: HEADER,
    // Toujours la version courante, jamais celle du fichier d'origine : on
    // n'écrit une résolution qu'après avoir résolu ou réparé ses cibles contre
    // l'observation d'AUJOURD'HUI. Conserver un `version: 1` sur un fichier
    // dont les cibles viennent d'être recalculées sous l'observation v2
    // mentirait sur ce qu'il contient — et rendrait muet, sur ce fichier même,
    // l'avertissement de version périmée.
    version: RESOLUTION_VERSION,
    scenario: resolution.scenario,
    platform: resolution.platform,
    recordedAt: resolution.recordedAt,
  };
  if (resolution.appVersion !== undefined) document['appVersion'] = resolution.appVersion;

  document['steps'] = Object.fromEntries(
    Object.entries(resolution.steps).map(([id, step]) => [id, orderStep(step)]),
  );

  return `${print(document, 0)}\n`;
}

export async function saveResolution(path: string, resolution: Resolution): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, serializeResolution(resolution), 'utf8');
}
